version: '3.2'
services:
  db:
    image: postgres:10.6-alpine
    env_file:
      - env_file
    volumes:
      - ./data:/data
    restart: unless-stopped
  mq:
    image: rabbitmq:3.7.8-alpine
    hostname: mq
    env_file:
      - env_file
    volumes:
        - ./queue:/q
    ports:
      - "15672"
      - "5672"
    restart: unless-stopped
  playback:
    build: ./munin_playback
    env_file:
      - env_file
    volumes:
      - type: bind
        source: ./archive 
        target: /playback/collections/munin/archive
        read_only: true
    ports:
      - "4445:8080"
    depends_on:
      - web
  web:
    build: ./munin_web
    env_file:
      - env_file
    command: sh -c './wait-for-db.sh'
    volumes:
      - ./munin_web/muninweb:/code
      - ./jobs:/jobs        
      - ./scripts:/scripts        
      - ./archive:/archive
      - ./deleted:/deleted
    ports:
      - "4444:8000"
    depends_on:
      - db
  worker:
    build: ./munin_indexer
    env_file:
      - env_file
    environment:
      - HTTPS_PROXY=socks5://torproxy:5566
      - HTTP_PROXY=socks5://torproxy:5566
    command: sh -c './wait-for.sh web:8000 -t 60 -- python worker.py'
    restart: unless-stopped
    depends_on:
      - web
      - mq
      - torproxy
  torproxy:
    image: negash/docker-haproxy-tor:latest
    hostname: torproxy
    ports:
      - "5566"
  archiveworker:
    build: ./munin_archiver
    env_file:
      - env_file
    volumes:
      - ./archive:/archive
      - ./jobs:/jobs        
      - ./scripts:/scripts        
    depends_on:
      - web
      - mq
    command: sh -c './wait-for.sh web:8000 -t 60 -- python worker.py'
    restart: unless-stopped
    shm_size: 1G
