version: '3'

services:
  db:
    image: postgres
    env_file:
      - env_file
    volumes:
      - ./data:/data
    restart: unless-stopped
  mq:
    image: rabbitmq:3.7.8-alpine
    hostname: mq
    env_file:
      - env_file
    volumes:
        - ./queue:/q
    ports:
      - "15672"
      - "5672"
    restart: unless-stopped
  web:
    build: ./munin_web
    env_file:
      - env_file
    command: sh -c './wait-for-db.sh'
    volumes:
      - ./munin_web/muninweb:/code
      - ./jobs:/jobs        
      - ./scripts:/scripts        
    ports:
      - "4444:8000"
    depends_on:
      - db
  worker:
    build: ./munin_indexer
    env_file:
      - env_file
    command: sh -c './wait-for.sh web:8000 -t 60 -- python worker.py'
    restart: unless-stopped
    depends_on:
      - web
      - mq
  archiveworker:
    build: ./munin_archiver
    env_file:
      - env_file
    volumes:
      - ./archive:/archive
      - ./jobs:/jobs        
      - ./scripts:/scripts        
    depends_on:
      - web
      - mq
    command: sh -c './wait-for.sh web:8000 -t 60 -- python worker.py'
    restart: unless-stopped
    shm_size: 1G
