# Generated by Django 2.1.1 on 2018-09-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='last_check',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='seed',
            name='state',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
