# Generated by Django 2.1.1 on 2018-09-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munin', '0003_auto_20180923_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='check_frequency',
            field=models.PositiveIntegerField(default=86400),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(db_index=True, max_length=4000, unique=True),
        ),
    ]
