# Generated by Django 2.1.1 on 2018-09-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munin', '0004_auto_20180926_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'Waiting'), (2, 'In queue')], default=1),
        ),
        migrations.AlterField(
            model_name='seed',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'Waiting'), (2, 'In queue')], default=1),
        ),
    ]
