# Generated by Django 2.1.1 on 2018-12-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munin', '0005_auto_20180930_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='warc_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='warc_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
