# Generated by Django 2.1.1 on 2018-12-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munin', '0006_auto_20181201_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='jobid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
