# Generated by Django 2.1.2 on 2018-12-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munin', '0008_post_retry_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warc_count', models.PositiveIntegerField(default=0)),
                ('warcs_created', models.PositiveIntegerField(default=0)),
                ('post_crawl_queue', models.PositiveIntegerField(default=0)),
                ('warc_size_total', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('seed_count', models.PositiveIntegerField(default=0)),
                ('post_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
