# Generated by Django 2.1.2 on 2018-12-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munin', '0009_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='warc_size_total',
            field=models.FloatField(default=0.0),
        ),
    ]
