# Generated by Django 2.1.2 on 2018-12-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munin', '0010_auto_20181207_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='seed_crawl_queue',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
