# Generated by Django 2.1.2 on 2018-12-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munin', '0011_stats_seed_crawl_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='deactivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seed',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
