# Generated by Django 2.1.2 on 2019-01-01 21:21

from django.db import migrations, models
from munin.extras import get_uid

def set_uid_defaults(apps, schema_editor):
    Post = apps.get_model('munin', 'Post')
    for post in Post.objects.all().iterator():
        post.uid = get_uid(post.url)
        print(f"Saving post {post.id}: uid: {post.uid}")
        post.save()

def reverse_func(apps, schema_editor):
    pass  

class Migration(migrations.Migration):

    dependencies = [
        ('munin', '0012_auto_20181227_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.CharField(db_index=True, help_text='Unique identifier for post as per the website deifnition', max_length=255, null=True),
        ),
        migrations.RunPython(set_uid_defaults, reverse_func),
        migrations.AlterField(
            model_name='post',
            name='uid',
            field=models.CharField(max_length=255, blank=False, null=False, db_index=True, help_text='Unique identifier for post as per the website deifnition'),
        ),
    ]
